baseURL = 'https://daocidi-site-share.github.io/lamrim/'
languageCode = 'zh-CN'
title = 'Daocidi Share Site'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'