baseURL = 'https://wisdomshare.dpdns.org'
languageCode = 'zh-CN'
title = 'Wisdom Share Site'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'